//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonBattle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        public int battleID { get; set; }
        public int tournamentID { get; set; }
        public int arenaID { get; set; }
        public int playerOneID { get; set; }
        public int playerTwoID { get; set; }
        public int winnerID { get; set; }
        public int logID { get; set; }
    
        public virtual Arena Arena { get; set; }
        public virtual Log Log { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Tournament Tournament { get; set; }
        public virtual Player Player2 { get; set; }
    }
}
