//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonBattle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.Teams = new HashSet<Team>();
            this.Teams1 = new HashSet<Team>();
            this.Teams2 = new HashSet<Team>();
            this.Teams3 = new HashSet<Team>();
            this.Teams4 = new HashSet<Team>();
            this.Teams5 = new HashSet<Team>();
        }
    
        public int pokemonID { get; set; }
        public string pokemonName { get; set; }
        public string pokemonDescription { get; set; }
        public int typeElementOneID { get; set; }
        public Nullable<int> typeElementTwoID { get; set; }
        public int movementOneID { get; set; }
        public int movementTwoID { get; set; }
        public int movementThreeID { get; set; }
        public int movementFourID { get; set; }
    
        public virtual Movement Movement { get; set; }
        public virtual Movement Movement1 { get; set; }
        public virtual Movement Movement2 { get; set; }
        public virtual Movement Movement3 { get; set; }
        public virtual TypeElement TypeElement { get; set; }
        public virtual TypeElement TypeElement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams5 { get; set; }
    }
}
