//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonBattle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int teamID { get; set; }
        public int pokemonOneID { get; set; }
        public int pokemonTwoID { get; set; }
        public int pokemonThreeID { get; set; }
        public int pokemonFourID { get; set; }
        public int pokemonFiveID { get; set; }
        public int pokemonSixID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        public virtual Pokemon Pokemon { get; set; }
        public virtual Pokemon Pokemon1 { get; set; }
        public virtual Pokemon Pokemon2 { get; set; }
        public virtual Pokemon Pokemon3 { get; set; }
        public virtual Pokemon Pokemon4 { get; set; }
        public virtual Pokemon Pokemon5 { get; set; }
    }
}
